# Setup
title:               'Hemeróc'
tagline:             'Engineer at Work'
description:         'Documenting the life of an engineer.'
url:                 https://hemeroc.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dominik Moser
  url:               https://twitter.com/HemerocDrakone

# Gems
plugins:
  - jekyll-paginate
