# Setup
title:               'Hemeróc'
tagline:             'Engineer at Work'
description:         ''
url:                 https://hemeroc.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dominik Moser
  url:               https://twitter.com/HemerocDrakone

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
